TEXTS = {
    'en': {
        'choose_lang': "Please select your language:",
        'welcome': "👋 Welcome to our Delivery Service!",
        'closed': "⛔ Sorry, we are currently closed. Open daily 6 AM – 6 PM.",
        'ask_phone': "📞 Please share your phone number to continue:",
        'btn_phone': "📱 Share Phone Number",
        'phone_saved': "✅ Phone number saved!",
        'choose_cafe': "☕ Choose a café:",
        'menu_header': "Menu for {}:",
        'added_cart': "🛒 Added: {} × {}\n✅ Press 'Done' when ready.",
        'cart_empty': "❗ Your cart is empty.",
        'item_not_found': "❌ Item not found.",
        'total': "💵 Total",
        'delivery_fee': "🚚 Delivery Fee",
        'ask_location': "📍 Please share your location to finalize:",
        'btn_location': "📍 Share Location",
        'btn_done': "✅ Done",
        'btn_cancel': "❌ Cancel Order",
        'btn_back': "🔙 Back",
        'order_sent': "✅ Order sent! Wait for confirmation.\n📦 Order No: `{}`",
        'order_cancelled': "❌ Order cancelled.",
        'location_error': "❌ Delivery is only available within Werabe city limits.",
        'admin_broadcast': "📢 Announcement:\n\n{}",
        'order_accepted': "✅ Your Order `{}` has been ACCEPTED! 🚚\nIt will be delivered shortly.",
        'order_declined': "❌ Your Order `{}` was DECLINED.\nPlease contact support or try again.",
        'btn_profile': "👤 My Profile",
        'profile_header': "👤 *User Profile*\n\n📞 Phone: `{}`\n🗣️ Language: English\n📍 Location: {}",
        'btn_switch_lang': "🔄 Switch Language",
        'btn_edit_phone': "✏️ Change Phone",
        'location_set': "Set ✅",
        'location_not_set': "Not Set ❌",
        'payment_request': "💳 *Payment Required*\n\nTotal Amount: *{} ETB*\nOrder ID: `{}`\n\nPlease complete the payment to confirm your order.",
        'btn_pay_now': "💳 Pay Now",
        'btn_verify_payment': "✅ Verify Payment",
        'payment_instructions': "📝 *Instructions:*\n1. Click 'Pay Now' button\n2. Complete payment on Chapa\n3. Return here and click 'Verify Payment'\n\nYour order will be processed after payment verification.",
        'payment_error': "❌ Payment service is currently unavailable. Please contact support.",
        'payment_init_error': "❌ Failed to initialize payment. Please try again or contact support.",
        'payment_success': "✅ Payment successful!\n\nYour order `{}` has been confirmed and sent to the kitchen. You will receive a confirmation shortly.",
        'payment_not_completed': "⏳ Payment not yet completed. Please complete the payment first, then verify.",
        'payment_verification_failed': "❌ Payment verification failed. Please try again or contact support if you've already paid.",
        'no_pending_order': "❌ No pending order found.",
        'payment_ref_mismatch': "❌ Payment reference mismatch. Please try again.",
        'verifying_payment': "⏳ Verifying your payment..."
    },
    'am': {
        'choose_lang': "እባክዎ ቋንቋ ይምረጡ / Please choose language:",
        'welcome': "👋 ወደ ዴሊቨሪ አገልግሎታችን እንኳን በደህና መጡ!",
        'closed': "⛔ ይቅርታ፣ አሁን ዝግ ነን። በየቀኑ ከጠዋቱ 12 ሰዓት እስከ ማታ 12 ሰዓት ክፍት ነን።",
        'ask_phone': "📞 ለመቀጠል እባክዎ ስልክ ቁጥርዎን ያጋሩ፡",
        'btn_phone': "📱 ስልክ ቁጥር ያጋሩ",
        'phone_saved': "✅ ስልክ ቁጥር ተመዝግቧል!",
        'choose_cafe': "☕ ካፌ ይምረጡ፡",
        'menu_header': "የ {} ሜኑ፡",
        'added_cart': "🛒 ተጨምሯል፡ {} × {}\n✅ ሲጨርሱ 'ጨርሻለሁ' የሚለውን ይጫኑ።",
        'cart_empty': "❗ ምንም ነገር አልመረጡም።",
        'item_not_found': "❌ እቃው አልተገኘም።",
        'total': "💵 ጠቅላላ",
        'delivery_fee': "🚚 የትራንስፖርት",
        'ask_location': "📍 ትዕዛዙን ለመጨረስ እባክዎ ያሉበትን ቦታ (Location) ያጋሩ፡",
        'btn_location': "📍 ቦታ ያጋሩ (Location)",
        'btn_done': "✅ ጨርሻለሁ",
        'btn_cancel': "❌ ሰርዝ",
        'btn_back': "🔙 ተመለስ",
        'order_sent': "✅ ትዕዛዝዎ ተልኳል! ማረጋገጫ እስኪደርስዎት ይጠብቁ።\n📦 የትዕዛዝ ቁጥር: `{}`",
        'order_cancelled': "❌ ትዕዛዝ ተሰርዟል።",
        'location_error': "❌ ዴሊቨሪ የምንሰጠው በወራቤ ከተማ ውስጥ ብቻ ነው።",
        'admin_broadcast': "📢 ማስታወቂያ፡\n\n{}",
        'order_accepted': "✅ ትዕዛዝ ቁጥር `{}` ተቀባይነት አግኝቷል! 🚚\nበቅርቡ ይደርስዎታል።",
        'order_declined': "❌ ትዕዛዝ ቁጥር `{}` ውድቅ ተደርጓል።\nእባክዎ ይደውሉልን።",
        'btn_profile': "👤 የእኔ መረጃ (Profile)",
        'profile_header': "👤 *የግል መረጃ*\n\n📞 ስልክ: `{}`\n🗣️ ቋንቋ: አማርኛ\n📍 አድራሻ: {}",
        'btn_switch_lang': "🔄 ቋንቋ ቀይር",
        'btn_edit_phone': "✏️ ስልክ ለመቀየር",
        'location_set': "ተመዝግቧል ✅",
        'location_not_set': "አልተመዘገበም ❌",
        'payment_request': "💳 *ክፍያ ያስፈልጋል*\n\nጠቅላላ መጠን: *{} ብር*\nየትዕዛዝ ቁጥር: `{}`\n\nትዕዛዝዎን ለማረጋገጥ እባክዎ ክፍያውን ያጠናቅቁ።",
        'btn_pay_now': "💳 አሁን ይክፈሉ",
        'btn_verify_payment': "✅ ክፍያ ያረጋግጡ",
        'payment_instructions': "📝 *መመሪያዎች:*\n1. 'አሁን ይክፈሉ' የሚለውን ይጫኑ\n2. በቻፓ ላይ ክፍያውን ያጠናቅቁ\n3. ወደዚህ ተመለስ እና 'ክፍያ ያረጋግጡ' ይጫኑ\n\nክፍያው ከተረጋገጠ በኋላ ትዕዛዝዎ ይቀርባል።",
        'payment_error': "❌ የክፍያ አገልግሎት አሁን አይገኝም። እባክዎ ድጋፍ ያግኙ።",
        'payment_init_error': "❌ ክፍያ ማስጀመር አልተሳካም። እባክዎ እንደገና ይሞክሩ ወይም ድጋፍ ያግኙ።",
        'payment_success': "✅ ክፍያው ተሳክቷል!\n\nየትዕዛዝ ቁጥር `{}` ተረጋግጧል እና ወደ ኩሽና ተልኳል። በቅርቡ ማረጋገጫ ይደርስዎታል።",
        'payment_not_completed': "⏳ ክፍያው እስካሁን አልተጠናቀቀም። እባክዎ በመጀመሪያ ክፍያውን ያጠናቅቁ፣ ከዚያም ያረጋግጡ።",
        'payment_verification_failed': "❌ የክፍያ ማረጋገጥ አልተሳካም። እባክዎ እንደገና ይሞክሩ ወይም ከዚህ በፊት ከከፈሉ ድጋፍ ያግኙ።",
        'no_pending_order': "❌ ምንም በመጠባበቅ ላይ ያለ ትዕዛዝ አልተገኘም።",
        'payment_ref_mismatch': "❌ የክፍያ ማመሳከሪያ አይጣጣምም። እባክዎ እንደገና ይሞክሩ።",
        'verifying_payment': "⏳ ክፍያዎን እያረጋገጥን ነው..."
    }
}

def get_text(lang, key):
    return TEXTS.get(lang, TEXTS['en']).get(key, TEXTS['en'].get(key, key))
